
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/flashmob/go-guerrilla"
  source = "github.com/athoune/go-guerrilla"
  branch = "dep"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "~0.9.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/onrik/logrus"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.8.0"