
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/flashmob/go-guerrilla"
  source = "github.com/athoune/go-guerrilla"
  branch = "dep"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "~0.9.0"